swagger: '2.0'
schemes:
  - http
  - https
host: oceanprotocol.com
basePath: /api/v1/keeper
info:
  $ref: ./info/index.yaml
tags:
  - name: actor
    description: Operations about actors
  - name: asset
    description: Operations about assets
  - name: curation
    description: Operations about curation
  - name: market
    description: Market operations
  - name: verification
    description: Operations about verifications
  - name: search
    description: Asset search
x-tagGroups:
  - name: Actor Management
    tags:
      - actor
  - name: Asset Management
    tags:
      - asset
  - name: Curation Management
    tags:
      - curation
  - name: Market Management
    tags:
      - market
  - name: Verification Management
    tags:
      - verification
  - name: Search interface
    tags:
      - search
securityDefinitions:
  protokeeper_auth:
    description: |
      Get access to data while protecting your account credentials.
      OAuth2 is also a safer and more secure way to give you access.
    type: oauth2
    authorizationUrl:
    flow: implicit
    scopes:
      'write:actors': modify actors
      'read:actors': read actors
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
